---

- name: Add the RabbitMQ release signing key to the apt trusted keys
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
           state=present

- name: Add the RabbitMQ repository to the apt sources list
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install RabbitMQ server
  apt:
    pkg:
      - rabbitmq-server
    update_cache: "{{ update_apt_cache }}"
    state: present

- name: Enable the RabbitMQ Management Console
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq-server

- name: Make sure rabbitmq-server is enabled and running
  service:
    name: rabbitmq-server
    state: started
    enabled: true

- include: setup_vhosts.yml

- include: setup_users.yml

- name: install logrotate configuration
  template:
    src: logrotate_rabbitmq.j2
    dest: /etc/logrotate.d/rabbitmq-server
  tags:
    - "install"
    - "install:app-configuration"
    - "logrotate"

- name: Ensure that the RabbitMQ service is running
  service: name=rabbitmq-server state=started enabled=yes