---

- name: Create the folder for the celery scripts
  file: path={{ celery_scripts_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        mode=0774
        state=directory

- name: Create the {{ celery_application_name }} script file
  template: src=worker.sh.j2
            dest={{ celery_scripts_dir }}/worker.sh
            owner={{ celery_user }}
            group={{ celery_group }}
            mode=0755
