---

- name: Add deadsnakes team New Python Versions PPA to the apt sources list
  apt_repository: repo='ppa:deadsnakes/ppa'
                  update_cache={{ update_apt_cache }}
                  state=present
  when: enable_deadsnakes_ppa

# yarn need cmdtest removed
- name: Remove "cmdtest" package
  apt:
    name: cmdtest
    state: absent

- name: Install additional packages
  apt:
    pkg:
      #- libav-tools
      - libcurl4-gnutls-dev
      - gnutls-dev
      - libpq-dev
      - nodejs
      - npm
      - "{{ virtualenv_python_version + '-dev' }}"
    update_cache: "{{ update_apt_cache }}"
    state: present
