---

# Virtualenv settings.
enable_deadsnakes_ppa: no
recreate_virtualenv: no
virtualenv_python_version: "{{ base_python_package }}"


# Application settings.
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Django db
run_django_syncdb: False

# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  BROKER_URL: "{{ broker_url }}"
