---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Install security updates
  become: yes
  become_user: root
  apt: default_release={{ ansible_distribution_release }}-security
       update_cache={{ update_apt_cache }}
       upgrade=dist
  tags:
    - packages
    - skip_ansible_lint

- name: Install base packages
  become: yes
  become_user: root
  apt:
    pkg:
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - "{{ base_python_package }}-pip"
    - "i{{ base_python_package }}"
    - python-virtualenv
    - supervisor
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags:
    - packages
    - packages.security

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
    - skip_ansible_lint
